openapi: 3.0.0
info:
  title: Especificacao Autenticacao de Usuario
  description: Especificação Autenticacao de Usuario
  contact:
    email: midialp2@gmail.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
  - url: https://development.teste-server.com/v1
    description: servidor de desenvolvimento
paths:
  /login:
    post:
      summary: Login do usuário
      operationId: "postLogin"
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/body_request'
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/body_response'
        "400":
          description: Dados request enviados incorretos
        "401":
          description: Password incorreto
        "404":
          description: Usuário não encontrado
        "500":
          description: Erro no servidor
components:
  schemas:
    body_request:
      required:
      - email
      - password
      type: object
      properties:
        email:
          minimum: 1
          type: string
          format: email
          example: admin@admin.com
        password:
          minimum: 1
          type: string
          format: password
          example: "1234"
    body_response:
      required:
      - email
      - id
      - name
      - surname
      - token
      type: object
      properties:
        token:
          minimum: 1
          type: string
          example: >-
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9
            .eyJlbWFpbCI6ImF5bGFuQGJvc2Nhcmluby5jb20iLCJwYXNzd29yZCI6InlhMGdzcWh5NHd6dnV2YjQifQ.yN_8-Mge9mFgsnYHnPEh_ZzNP7YKvSbQ3Alu
        account:
          type: string
          example: '{"id":1,"email":"mariajose@mariajose.com","name":"Maria","surname":"José"}'
